-- ITEM_INFO : ITEM_ID, ITEM_NAME, RARITY, PRICE
-- ITEM_TREE : ITEM_ID, PARENT_ITEM_ID
-- 희귀도가 RARE인 아이템들의 모든 다음 업그레이드 아이템의 ID, NAME, RARITY를 출력
-- 결과는 ID기준 내림차순
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN 
    (SELECT ITEM_ID
      FROM ITEM_TREE
      WHERE PARENT_ITEM_ID IN
     (SELECT ITEM_ID 
     FROM ITEM_INFO
     WHERE RARITY = "RARE"
      )
    )
ORDER BY ITEM_ID DESC