-- 코드를 작성해주세요
-- ITEM_INFO & ITEM_TREE 
-- 아이템의 희귀도가 RARE인 아이템들의 모든 다음 업그레이드 아이템의 아이템 INFO 출력

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT T.ITEM_ID
        FROM ITEM_INFO I, ITEM_TREE T
        WHERE I.ITEM_ID = T.PARENT_ITEM_ID AND I.RARITY = 'RARE')
ORDER BY ITEM_ID DESC